const test = require("./model/SophyDB")

const mongo = new test()
mongo.connect(async (client)=>{
    console.log("Comenzando consultas")
    let values = await mongo.selectPlace()
    console.log(values)
    values = await mongo.selectAllPlace()
    console.log(values)
    // let insert = await mongo.insertPlace({name:"DOC"})
    // console.log(insert)
    // insert = await mongo.insertPlace({name:"DOC1"})
    // console.log(insert)
    // insert = await mongo.insertPlace({name:"DOC2"})
    // console.log(insert)
    // insert = await mongo.insertPlace({name:"DOC3"})
    // console.log(insert)
    // insert = await mongo.insertPlace({name:"DOC4"})
    // console.log(insert)
    // values = await mongo.selectPlace()
    // console.log(values)
    mongo.closeConnection()
})
